services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'cloudwirm_db'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_storage:/data

volumes:
  mysql-data:
  minio_storage: